name: shoppinglist-client-browser

services:
  client-browser:
    container_name: sl-client-browser
    image: ${DOCKER_REGISTRY-}shoppinglist-client-browser
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: unless-stopped
