apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-list-client
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: shopping-list.example.com  # Замените на production домен
  tls:
  - hosts:
    - shopping-list.example.com  # Замените на production домен
    secretName: shopping-list-tls
