apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../deployment.yaml
  - ../service.yaml
  - ../ingress.yaml
  - ../configmap.yaml
  - ../hpa.yaml
  - ../pdb.yaml

commonLabels:
  app: shopping-list-client
  component: frontend
  managed-by: kustomize
